### ISSUE TITLE
Update the README.md file

### ISSUE THREAD

**Issue by harshit98** [harshit98/Optical-Smoke-Detector#1]
Update the README file with the sufficient information regarding the project:
- Description of the project.
- Components to be used.

Here is the list of the components which will be used:
- 4.7K and 10K potentiometer.
- IC LM358.
- IC MOC7811.
- Resistors: 100 ohms, 680 ohms, 33K, 10K.
- Two transistors BC547A.
- 1 LED.
- 1 Capacitor 100 microfarad, 25 volts.
- 1 electric buzzer.

**Comment by harryjas** [comment]
@harshit98 I would like to make a README.md file

**Comment by harryjas** [comment]
@harshit98 I would like to update README.md file.

**Comment by harshit98** [comment]
Hi @harryjas. Sure. Please go ahead. :)

**Comment by Yachee123** [comment]
Hi ! I am interested in updating the README and with all the components and information regarding the project.

**Comment by harshit98** [comment]
Hi @Yachee123. The README issue has been done already. You can help me in solving other issues :)
